config/routes.rb
KontNoor::Application.routes.draw do
  resources :pages
  match '/:id' => 'pages#show'

  get "home/index"

  root :to => 'home#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :get_pages_list
  protect_from_forgery

  def get_pages_list
    @pages = Page.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page = Page.find_or_create_by_url('home')
    @pages = Page.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by_url(params[:id])
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.find(params[:id])
  end

  def create
    @page = Page.new(params[:page])

    if @page.save
      redirect_to page_path(@page.url), :notice => 'Page was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @page = Page.find(params[:id])

    if @page.update_attributes(params[:page])
      redirect_to page_path(@page.url), :notice => 'Page was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    redirect_to pages_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<h1><%= @page.title %></h1>
<p id="notice"><%= notice %></p>
<p><%= @page.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
	<title>Kont Noor's main page</title>
    <%= csrf_meta_tag %>
    <link rel="stylesheet" type="text/css" href="/css/all.css" media="all"/>
	<!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen"/><![endif]-->
</head>
<body>
	<div id="main">
		<div id="center">
			<div class="content">
				<%= yield %>
			</div>
			<div class="sidebar">
				<ul>
				    <% @pages.each do |page| %>
                    <li><%= link_to page.title, '/'+page.url %></li>
                    <% end %>
				</ul>
			</div>
		</div>
		<div id="header">
			<strong class="logo"><%= image_tag "logo.gif", {:alt => "Чого вилупився?"} %></strong>
			<em class="title">Офіційний сайт Конта Ноорського,<br />сусіда Олексія Мангупського</em>
		</div>
	</div>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Description</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.url %></td>
    <td><%= page.description %></td>
    <td><%= page.content %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p id="notice"><%= notice %></p>
<p><%= @page.content %></p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>